# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iOS Example' do

pod 'pmaToolkit', :git => 'git@bitbucket.org:peteralt_pma/pmatoolkit.git'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

end


